export const ADDTASK="TODO/ADDTASK";
export const DELETE="TODO/DELETE";
export const GETTASK="TODO/GETTASK";
export const UPDATESTATUS="TODO/UPDATETASKSTATUS";
export const UPDATETASK="TODO/UPDATETASK";
export const DELETEHISTORY="TODO/DELETEHISTORY";